name: Benchmark

on:
  push:
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-codspeed
      run: cargo install cargo-codspeed
    - name: Run the benchmarks
      uses: CodSpeedHQ/action@v2
      with:
        run: cargo codspeed run
        token: ${{ secrets.CODSPEED_TOKEN }}
